version: 0.2
run-as: root

  
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.......
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r8c4o2p7
      - # Replace with this to your repository URI
      - REPOSITORY_URL=public.ecr.aws/r8c4o2p7/node-test-app
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - echo Build started on `date`
      - echo Docker image is building....... 
      - npm --version
      - npm install express
      - npm install prom-client
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to AWS ECR .....
      - docker push $REPOSITORY_URL:$IMAGE_TAG 
      - echo ECS Configuration....
      - echo Writing image definitions file...
      - CONTAINER_NAME=nodeapp-container
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json   
artifacts:
    files: imagedefinitions.json
